# バージョンの指定
version: "3"

# サービス定義
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file: .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db-data:/var/lib/mysql
      - ./sql/test_data_mysql.sql:/docker-entrypoint-initdb.d/test_data_mysql.sql
  web:
    build: ./docker/httpd
    ports:
      - "10080:80"
    volumes:
      - ./mt-setting.sh:/var/www/mt-setting.sh
      - ./www/html:/var/www/html
      - ./www/logs:/var/www/log
      - ./mtml:/var/www/local/cgi-bin/mt/themes
      - ./mt-static/mtml:/var/www/local/cgi-bin/mt/mt-static/themes
      - ./docker/httpd/conf/virtualhost.conf:/etc/httpd/conf.d/virtualhost.conf
      - ./docker/httpd/mt-settings/mt-config.cgi:/var/www/local/cgi-bin/mt/mt-config.cgi
    # environment:
    #   MT_DATABASE_NAME: ${MYSQL_DATABASE}
    #   MT_DATABASE_USERNAME: ${MYSQL_USER}
    #   MT_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    #   MT_DBHost: mysql
    env_file: .env
    depends_on:
      - mysql
volumes:
  db-data:
    driver: local