# バージョンの指定
version: "3"

# サービス定義
services:
  mysql:
    container_name: ${CONTAINER_BASE_NAME}-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file: .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db-data:/var/lib/mysql
      - ./sql/test_data_mysql.sql:/docker-entrypoint-initdb.d/test_data_mysql.sql
  web:
    container_name: ${CONTAINER_BASE_NAME}-apache
    build: ./docker
    ports:
      - "${PORT}"
    volumes:
      - ./www/html:/var/www/local/html
      - ./www/logs:/var/www/local/logs
      - ./mtml:/var/www/local/cgi-bin/mt/themes
      - ./mt-settings/mt-config.cgi:/var/www/local/cgi-bin/mt/mt-config.cgi
      - ./docker/httpd/virtualhost.conf:/etc/httpd/conf.d/virtualhost.conf
    depends_on:
      - mysql
